#pragma once
#include "./function_declaration.hpp"
#include "./expression.hpp"
#include "./call_function_action.hpp"
#include "./variable_declaration.hpp"
#include "./number.hpp"
#include "./operation.hpp"
#include "./binary_operator_action.hpp"
#include "./unary_operator_action.hpp"
